### PR TITLE
Fix source code warnings produced by Xcode 9

### PR DESCRIPTION
**Pull request by mpdifran-Bridgit**
Specify void in block parameter lists

### CODE REVIEW

**Review by isadon — COMMENTED** [review]
Seems you forgot lines 53 and 55 of RMessageView.m. Also can you rename your PR to be "Fix source code warnings produced by Xcode 9". There are some project warnings also generated which I have to apply a commit for and want to differentiate with this commit.

**Review by isadon — COMMENTED** [review]
There are still warnings generated in lines 53, 55 of RMessageView.m. Please fix those before I can merge.

**Comment by mpdifran-Bridgit** [comment]
Sorry, must have gotten distracted while in the middle of committing. Should be there now.

**Review by isadon — APPROVED** [review]
Thanks.

**Pull request merged**
