### PR TITLE
If a custom image is not found try to load it from the app bundle.

### PR DESCRIPTION
**Pull request by baspellis**
When an image name is specified in the custom design file the images will be loaded from the RMessageView bundle. Using this PR, if this image is not found it will try to load it from the app Bundle. This makes it possible to provide custom images in the app Bundle.

### CODE REVIEW

**Comment by isadon** [comment]
Thanks for the PR. Can you change this to the develop branch instead?

**Comment by baspellis** [comment]
There are two other commits (43e4a37 and 39b5b91) on the develop branch not merged in master yet. These should be merged first, otherwise they will be included in this PR.

**Comment by isadon** [comment]
The contents of those mentioned commits are merged on master. Regardless you should base your changes on the develop branch as all merges and changes are made there first.

**Comment by baspellis** [comment]
Ok done.

**Comment by isadon** [comment]
Thanks. Can you also remove lines 703-705 from RMessageView.m as they are no longer needed as part of this PR?

**Comment by baspellis** [comment]
Yes that's done now too

**Comment by isadon** [comment]
Looks Good. Merging Now.

**Pull request merged**
