### PR TITLE
Swift 4.2 Compatibility Changes

### PR DESCRIPTION
**Pull request by mbabker**
Swift 4.2 renamed a number of constants which impacts this package.  This pull request updates the use of the renamed constants, and as a result bumps the minimum Swift version to 4.2.

### CODE REVIEW

**Comment by isadon** [comment]
Thanks. Wont bumping to 4.2 in the pod spec require users of RMessage be on Swift 4.2 however?

**Comment by mbabker** [comment]
Not necessarily.  I ran into something on some other GitHub issue that points out you can set a specific Swift version for a pod to use.  So in this case, my main app and all pods default to Swift 5 and this pod is building with Swift 4.1 and it's just working.

```

swift_4_1_pod_targets = ['RMessage']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift_4_1_pod_targets.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.1'
      else
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
```

Of course it'd be preferable for everyone to update, but if they can't they can also stay pinned to an older version of the pod (similar to how if you're still supporting iOS 10 and earlier you need to use the last 2.x release).

**Comment by isadon** [comment]
I think what I’m saying is correct though. The code changes in this PR would only be supported by users on Swift 4.2 and above. Anyone on less than that would have to use the code prior to this PR. The code as it is now though does work though right? Just gives compatibility warnings?

**Comment by mbabker** [comment]
Right, if the changes in this PR are taken as is then the next version of this pod would only be compatible with Swift 4.2 and newer, and it's basically because of the constants being renamed.  It looks like it'd be possible to conditionally deal with it if you wanted to go that route.

Vars are probably easy to sort out:

```swift
#if swift(>=4.2)
var viewAttribute: NSLayoutConstraint.Attribute
var layoutGuideAttribute: NSLayoutConstraint.Attribute
#else
var viewAttribute: NSLayoutAttribute
var layoutGuideAttribute: NSLayoutAttribute
#endif
```

Functions, on the other hand, basically require code duplication:

```swift
#if swift(>=4.2)
private func setup(attributedTitleLabel titleLabel: UILabel, withAttributes attrs: [NSAttributedString.Key: Any]) {
  guard let titleText = titleLabel.text else { return }

  let titleAttributedText = NSAttributedString(string: titleText, attributes: attrs)
  titleLabel.attributedText = titleAttributedText
}
#else
private func setup(attributedTitleLabel titleLabel: UILabel, withAttributes attrs: [NSAttributedStringKey: Any]) {
  guard let titleText = titleLabel.text else { return }

  let titleAttributedText = NSAttributedString(string: titleText, attributes: attrs)
  titleLabel.attributedText = titleAttributedText
}
#endif
```

(Luckily, the affected functions are only 3 lines of code, so not that big of a hassle right now, but could be painful in the future if you had these types of conditionals on larger chunks)

**Comment by isadon** [comment]
Thanks. I'm thinking of just keeping this PR open for now till the right time to leave behind support for Swift 4.1 comes - at that time I will merge. It just doesn't seem worth the tradeoff to up the required Swift compiler version without actually using any new Swift > 4.1 features for the sake of just getting rid of some compiler warnings at the moment.

You are right though the approach above can be done but then it'd just be to get rid of some warnings which I don't see as that high a priority at the moment.

**Comment by isadon** [comment]
I'll close this PR out since the latest develop brings in changes to support Swift5.

**Pull request closed without merging**
